version: '2'
services:
  postgres:
    build: postgres
    ports:
      - "5432:5432"

  generator:
    build: inventory-generator

  elasticsearch:
    image: elasticsearch:6.4.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"

  kibana:
    image: kibana:6.4.1
    ports:
      - "5601:5601"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: warehouse-stock:4:1,warehouse-allocation:4:1,global-stock:4:1,stock-global-percentage:4:1,connect_test.public.warehouse:4:1,connect_test.public.stockquantity:4:1,connect_test.public.stockitem:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  streams:
    build: kafka-streams-app

  ksql:
    build: ksql
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_SERVICE_ID: ksql
      KSQL_LISTENERS: http://0.0.0.0:8088/

  connect:
    build: connect
    ports:
      - "8083:8083"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONNECT_GROUP_ID: connect-cluster
      KAFKA_CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      KAFKA_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      KAFKA_CONNECT_OFFSET_STORAGE_PARTITIONS: 2
      KAFKA_CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      KAFKA_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      KAFKA_CONNECT_STATUS_STORAGE_TOPIC: connect-status
      KAFKA_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      KAFKA_CONNECT_STATUS_STORAGE_PARTITIONS: 1
      KAFKA_CONNECT_REST_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_CONNECT_PLUGIN_PATH: /opt/kafka/connectors
      KAFKA_CONNECT_OFFSET_FLUSH_INTERVAL_MS: 60000
      KAFKA_CONNECT_TASK_SHUTDOWN_GRACEFUL_TIMEOUT_MS: 10000
      KAFKA_CONNECT_OFFSET_FLUSH_TIMEOUT_MS: 5000
      KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
