version: '2'
services:
  postgres:
    build: postgres
    ports:
      - "5432:5432"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  connect:
    build: connect
    ports:
      - "8083:8083"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CONNECT_GROUP_ID: connect-cluster
      KAFKA_CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      KAFKA_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 2
      KAFKA_CONNECT_OFFSET_STORAGE_PARTITIONS: 4
      KAFKA_CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      KAFKA_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 2
      KAFKA_CONNECT_STATUS_STORAGE_TOPIC: connect-status
      KAFKA_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 2
      KAFKA_CONNECT_STATUS_STORAGE_PARTITIONS: 2
      KAFKA_CONNECT_REST_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_CONNECT_PLUGIN_PATH: /opt/kafka/connectors
      KAFKA_CONNECT_OFFSET_FLUSH_INTERVAL_MS: 60000
      KAFKA_CONNECT_TASK_SHUTDOWN_GRACEFUL_TIMEOUT_MS: 10000
      KAFKA_CONNECT_OFFSET_FLUSH_TIMEOUT_MS: 5000
