#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE connect_test;
    \connect connect_test;

    CREATE TABLE StockItem (
        id              int PRIMARY KEY,
        description     varchar(40) NOT NULL
    );

    CREATE TABLE StorageNode (
        id          int PRIMARY KEY,
        name        varchar(40) NOT NULL
    );

    CREATE TABLE StorageNodeActivity (
        id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        storageNodeId       int NOT NULL REFERENCES StorageNode,
        stockItemId         int NOT NULL REFERENCES StockItem,
        moment              timestamp NOT NULL,
        quantity            int NOT NULL
    );
EOSQL