#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE connect_test;
    \connect connect_test;

    CREATE TABLE StockItem (
        id              int PRIMARY KEY,
        description     varchar(40) NOT NULL
    );

    CREATE TABLE Warehouse (
        id                  int PRIMARY KEY,
        name                varchar(40) NOT NULL,
        latitude            real NOT NULL,
        longitude           real NOT NULL,
        storageCapacity     int NOT NULL
    );

    CREATE TABLE StockSupply (
        id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        warehouseId         int NOT NULL REFERENCES Warehouse,
        stockItemId         int NOT NULL REFERENCES StockItem,
        quantity            int NOT NULL
    );

    CREATE TABLE StockDemand (
        id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        warehouseId         int NOT NULL REFERENCES Warehouse,
        stockItemId         int NOT NULL REFERENCES StockItem,
        quantity            int NOT NULL
    );

    CREATE TABLE StockReservation (
        id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        warehouseId         int NOT NULL REFERENCES Warehouse,
        stockItemId         int NOT NULL REFERENCES StockItem,
        quantity            int NOT NULL
    );
EOSQL