#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE connect_test;
    \connect connect_test;

    CREATE TABLE StockItem (
        number          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        description     varchar(40) NOT NULL
    );

    CREATE TABLE StorageNode (
        code        varchar(5) PRIMARY KEY,
        name        varchar(40) NOT NULL
    );

    CREATE TABLE StorageNodeActivity (
        id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stockItemNumber     int NOT NULL REFERENCES StockItem,
        storageNodeCode     varchar(5) NOT NULL REFERENCES StorageNode,
        moment              timestamp NOT NULL,
        quantity            int NOT NULL
    );
EOSQL